package servlet;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

public class HTMLServlet extends HttpServlet {

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        try {
            out.print("<!DOCTYPE html>"
                    + "<html>"
                    + "<head>"
                    + "<meta charset='utf-8'>"
                    + "<title>Java Programming for Kids, Parents and Grandparents by Yakov Fain</title>"
                    + "<meta name='description' content=''>"
                    + "<meta name='viewport' content='width=device-width, initial-scale=1'>"
                    + "<link rel='stylesheet' href='assets/css/final-2.css'>"
                    + "</head>"
                    + "<body>"
                    + "<div class='container cleafix'>"
                    + "<header>"
                    + "<h1>Java Programming for Kids, Parents and Grandparents</h1>"
                    + "<span>by</span> <span class='author'>Yakov Fain</span>"
                    + "</header>"
                    + "<div class='covers cleafix'>"
                    + "<div class='main'>"
                    + "<div>"
                    + "<a href='http://myflex.org/books/java4kids/JavaKid811.pdf'>"
            + "<img src='http://myflex.org/books/java4kids/images/cover1.JPG'>"
            + "</a>"
//                    + "<a class="download-link" href="http://myflex.org/books/java4kids/JavaKid811.pdf">"
//            + "English"
//                    + "</a>"
//                    + "</div>"
//                    + "<div>"
//                    + "<a href="http://myflex.org/books/java4kids/JavaEnfants.pdf">"
//            + "<img src="assets/img/JavaEnfants-1.jpg"></a>"
//                    + "<a class="download-link" href="http://myflex.org/books/java4kids/JavaEnfants.pdf">"
//            + "French"
//                    + "</a>"
//                    + "</div>"
//                    + "<div>"
//                    + "<a href="http://myflex.org/books/java4kids/JavaKid8x11_ru.pdf">"
//            + "<img src="assets/img/JavaKid8x11_ru-1.jpg"></a>"
//                    + "<a class="download-link" href="http://myflex.org/books/java4kids/JavaKid8x11_ru.pdf">"
//            + "Russian"
//                    + "</a>"
//                    + "</div>"
//                    + "<div>"
//                    + "<a href="http://myflex.org/books/java4kids/JavaKid_ua.zip">"
//            + "<img src="assets/img/JavaKid_ua-1.jpg"></a>"
//                    + "<a class="download-link" href="http://myflex.org/books/java4kids/JavaKid_ua.zip">"
//            + "Ukranian"
//                    + "</a>"
//                    + "</div>"
//                    + "</div>"
//                    + "<div class="aside">"
//                    + "<h2>free download</h2>"
//                    + "<p>"
//                    + "The complete e-book is available for free download in English, French, Russian, and Ukranian."
//                    + "</p>"
//                    + "<h4><i class="icon-pdf"></i> Sample chapter</h4>"
//                    + "<a class="download-link" href="http://myflex.org/books/java4kids/Chapter3_de.pdf">"
//            + "German"
//                    + "</a>"
//                    + "<a class="download-link" href="http://myflex.org/books/java4kids/Chapter3_ita.pdf">"
//            + "Italian"
//                    + "</a>"
//                    + "<a class="download-link" href="http://myflex.org/books/java4kids/Chapter3_swe.pdf">"
//            + "Swedish"
//                    + "</a>"
//                    + "<a class="download-link" href="http://myflex.org/books/java4kids/Chapter3_hebrew.pdf">"
//            + "Hebrew"
//                    + "</a>"
//                    + "<h4><i class="icon-code"></i> Code examples</h4>"
//                    + "<p>"
//                    + "<a class="download-link" href="http://myflex.org/books/java4kids/jfk_code.zip"> Code samples </a>"
//            + "</div>"
//                    + "</div>"
//
//                    + "<div class="about cleafix">"
//                    + "<div class="main">"
//                    + "<h2>Who this book is for</h2>"
//                    + "<ul>"
//                    + "<li>This e-book is for kids from 12 to 80 years old.</li>"
//                    + "<li>This e-book is great for parents who want to get their child into the world of computer"
//                    + "programming – the real one, not the reader-rabbit-kind-of-world."
//                    + "</li>"
//                    + "<li>This e-book is for college students who are looking for a supplement to overcomplicated"
//                    + "textbooks."
//                    + "</li>"
//                    + "<li>This e-book is easy enough for complete beginners of all ages.</li>"
//                    + "</ul>"
//                    + "</div>"
//                    + "<div class="aside">"
//                    + "<div class="about-new">"
//                    + "<h2 class="new">The New Edition (2015)</h2>"
//                    + "<p>"
//                    + "The new edition of the book is called Java Programming for Kids, and it covers the latest syntax of"
//                    + "Java 8 and the JavaFX8 framework</b>"
//                    + "</p>"
//                    + "<p>"
//                    + "For now only the English version of the book is available."
//                    + "</p>"
//                    + "<a class="draft-link" href="http://yfain.github.io/Java4Kids">"
//            + "Read it here"
//                    + "</a>"
//                    + "</div>"
//                    + "</div>"
//                    + "</div>"
//
//                    + "<footer>"
//                    + "Copyright &copy; 2014, Yakov Fain"
//                    + "</footer>"
//                    + "</div>"
                    + "</body>"
                    + "</html>");
            
        } finally {
            out.close();
        }
    }
}
